name: Actualizar el listado de los nuevos retos completados en el README.md 
    
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name javiluli
        git config user.email javiluli.dev@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] se actualiza la lista de challenges del README"
        git push origin master
